//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""BasicActions"",
            ""id"": ""49673c4a-fd08-40af-aba0-e2d872461fef"",
            ""actions"": [
                {
                    ""name"": ""Walk"",
                    ""type"": ""Value"",
                    ""id"": ""60bb03c2-cd00-44f5-950f-64fe4d574694"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""729bbc02-0656-4432-9a65-83a20ee24410"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Smell"",
                    ""type"": ""Button"",
                    ""id"": ""7bd88942-5dcf-4cb3-ba9a-5d8c872490ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Water"",
                    ""type"": ""Button"",
                    ""id"": ""afd0a0ad-0dc1-4010-aadc-a8473eb72391"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""576aed60-fcb8-4234-a8a4-fb3a56474357"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29bfd747-f935-4d0d-b7a6-dbc17db86752"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Smell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7cdb7e04-88a8-4c1e-85fc-6d2b90dccefb"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Smell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3339fa34-374d-4c8d-90b0-4fc99df6cb57"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Water"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54cee741-dc57-4bf5-b638-37382837c6a9"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Water"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c878e934-2329-4cf3-a2d1-4e3b9b29303b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b3d0d95f-ea7b-48aa-946c-33ef2c0447a7"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b68dc1f5-b1aa-48b5-9e11-9d8e910d6503"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bec3426f-aac9-4306-bfe4-8742f6a97b9d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e01dc138-7c8c-4fca-8030-b0a7f8b5d8de"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""MiniGameActions"",
            ""id"": ""d2a36738-6bcd-4ada-b420-d9a931d439b0"",
            ""actions"": [
                {
                    ""name"": ""StopTimingBar"",
                    ""type"": ""Button"",
                    ""id"": ""809dee25-ecf9-4fe0-96a2-5622d970f92a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""391dc69c-e008-4056-addb-0fe8035924c2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StopTimingBar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // BasicActions
        m_BasicActions = asset.FindActionMap("BasicActions", throwIfNotFound: true);
        m_BasicActions_Walk = m_BasicActions.FindAction("Walk", throwIfNotFound: true);
        m_BasicActions_Run = m_BasicActions.FindAction("Run", throwIfNotFound: true);
        m_BasicActions_Smell = m_BasicActions.FindAction("Smell", throwIfNotFound: true);
        m_BasicActions_Water = m_BasicActions.FindAction("Water", throwIfNotFound: true);
        // MiniGameActions
        m_MiniGameActions = asset.FindActionMap("MiniGameActions", throwIfNotFound: true);
        m_MiniGameActions_StopTimingBar = m_MiniGameActions.FindAction("StopTimingBar", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BasicActions
    private readonly InputActionMap m_BasicActions;
    private IBasicActionsActions m_BasicActionsActionsCallbackInterface;
    private readonly InputAction m_BasicActions_Walk;
    private readonly InputAction m_BasicActions_Run;
    private readonly InputAction m_BasicActions_Smell;
    private readonly InputAction m_BasicActions_Water;
    public struct BasicActionsActions
    {
        private @PlayerControls m_Wrapper;
        public BasicActionsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Walk => m_Wrapper.m_BasicActions_Walk;
        public InputAction @Run => m_Wrapper.m_BasicActions_Run;
        public InputAction @Smell => m_Wrapper.m_BasicActions_Smell;
        public InputAction @Water => m_Wrapper.m_BasicActions_Water;
        public InputActionMap Get() { return m_Wrapper.m_BasicActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BasicActionsActions set) { return set.Get(); }
        public void SetCallbacks(IBasicActionsActions instance)
        {
            if (m_Wrapper.m_BasicActionsActionsCallbackInterface != null)
            {
                @Walk.started -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnWalk;
                @Walk.performed -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnWalk;
                @Walk.canceled -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnWalk;
                @Run.started -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnRun;
                @Smell.started -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnSmell;
                @Smell.performed -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnSmell;
                @Smell.canceled -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnSmell;
                @Water.started -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnWater;
                @Water.performed -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnWater;
                @Water.canceled -= m_Wrapper.m_BasicActionsActionsCallbackInterface.OnWater;
            }
            m_Wrapper.m_BasicActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Walk.started += instance.OnWalk;
                @Walk.performed += instance.OnWalk;
                @Walk.canceled += instance.OnWalk;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @Smell.started += instance.OnSmell;
                @Smell.performed += instance.OnSmell;
                @Smell.canceled += instance.OnSmell;
                @Water.started += instance.OnWater;
                @Water.performed += instance.OnWater;
                @Water.canceled += instance.OnWater;
            }
        }
    }
    public BasicActionsActions @BasicActions => new BasicActionsActions(this);

    // MiniGameActions
    private readonly InputActionMap m_MiniGameActions;
    private IMiniGameActionsActions m_MiniGameActionsActionsCallbackInterface;
    private readonly InputAction m_MiniGameActions_StopTimingBar;
    public struct MiniGameActionsActions
    {
        private @PlayerControls m_Wrapper;
        public MiniGameActionsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @StopTimingBar => m_Wrapper.m_MiniGameActions_StopTimingBar;
        public InputActionMap Get() { return m_Wrapper.m_MiniGameActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MiniGameActionsActions set) { return set.Get(); }
        public void SetCallbacks(IMiniGameActionsActions instance)
        {
            if (m_Wrapper.m_MiniGameActionsActionsCallbackInterface != null)
            {
                @StopTimingBar.started -= m_Wrapper.m_MiniGameActionsActionsCallbackInterface.OnStopTimingBar;
                @StopTimingBar.performed -= m_Wrapper.m_MiniGameActionsActionsCallbackInterface.OnStopTimingBar;
                @StopTimingBar.canceled -= m_Wrapper.m_MiniGameActionsActionsCallbackInterface.OnStopTimingBar;
            }
            m_Wrapper.m_MiniGameActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @StopTimingBar.started += instance.OnStopTimingBar;
                @StopTimingBar.performed += instance.OnStopTimingBar;
                @StopTimingBar.canceled += instance.OnStopTimingBar;
            }
        }
    }
    public MiniGameActionsActions @MiniGameActions => new MiniGameActionsActions(this);
    public interface IBasicActionsActions
    {
        void OnWalk(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnSmell(InputAction.CallbackContext context);
        void OnWater(InputAction.CallbackContext context);
    }
    public interface IMiniGameActionsActions
    {
        void OnStopTimingBar(InputAction.CallbackContext context);
    }
}
